### ISSUE TITLE
Error: ENOENT, no such file or directory './sql/views.sql'

### ISSUE THREAD

**Issue by charyorde** [tjwebb/pg-json-schema-export#5]
Hi,

Node couldn't load views.sql file within the sql directory. 

Here's the console error log below:

```
bash-3.2$ node mgrt_pg_to_mongo.js

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './sql/views.sql'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/Users/charyorde/projects/nodescripts/node_modules/pg-json-schema-export/index.js:7:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/charyorde/projects/nodescripts/mgrt_pg_to_mongo.js:1:84)
```
Env:
- node v0.10.25
- OSX 8

**Comment by tjwebb** [comment]
any update?

**Comment by charyorde** [comment]
I did a number of workarounds to get this working. I can't remember much of it any longer though. But one of it should be installing locally instead of globally.

**Comment by tjwebb** [comment]
Yea... installing npm packages globally usually isn't going to work. It'd be nice in the future if you'd report the issues instead of silently hacking together workarounds that no one else can use.

**Comment by tjwebb** [comment]
Like I said, in the future, file issues before implementing random hacks to
make stuff work.
